"""Initial

Revision ID: 797f13d6aca7
Revises: 
Create Date: 2026-05-18 17:00:18.169974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797f13d6aca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiau_mur',
    sa.Column('id_materiau_mur', sa.Integer(), nullable=False),
    sa.Column('code_materiau', sa.String(length=20), nullable=False),
    sa.Column('libelle_materiau', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_materiau_mur'),
    sa.UniqueConstraint('code_materiau')
    )
    op.create_table('materiau_toit',
    sa.Column('id_materiau_toit', sa.Integer(), nullable=False),
    sa.Column('code_materiau', sa.String(length=20), nullable=False),
    sa.Column('libelle_materiau', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_materiau_toit'),
    sa.UniqueConstraint('code_materiau')
    )
    op.create_table('profession',
    sa.Column('id_profession', sa.Integer(), nullable=False),
    sa.Column('code_profession', sa.String(length=30), nullable=False),
    sa.Column('libelle_profession', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_profession'),
    sa.UniqueConstraint('code_profession')
    )
    op.create_table('source_eau',
    sa.Column('id_source_eau', sa.Integer(), nullable=False),
    sa.Column('code_source', sa.String(length=20), nullable=False),
    sa.Column('libelle_source', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_source_eau'),
    sa.UniqueConstraint('code_source')
    )
    op.create_table('statut_menage',
    sa.Column('id_statut_menage', sa.Integer(), nullable=False),
    sa.Column('code_statut', sa.String(length=30), nullable=False),
    sa.Column('libelle_statut', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_statut_menage'),
    sa.UniqueConstraint('code_statut')
    )
    op.create_table('statut_passage',
    sa.Column('id_statut_passage', sa.Integer(), nullable=False),
    sa.Column('code_statut', sa.String(length=30), nullable=False),
    sa.Column('libelle_statut', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_statut_passage'),
    sa.UniqueConstraint('code_statut')
    )
    op.create_table('type_localite',
    sa.Column('id_type_localite', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('libelle_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_localite'),
    sa.UniqueConstraint('code_type')
    )
    op.create_table('type_logement',
    sa.Column('id_type_logement', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('libelle_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_logement'),
    sa.UniqueConstraint('code_type')
    )
    op.create_table('type_toilette',
    sa.Column('id_type_toilette', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('libelle_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_toilette'),
    sa.UniqueConstraint('code_type')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('ADMINISTRATEUR','SUPERVISEUR','ENQUETEUR')", name='ck_utilisateur_role'),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('localite_administrative',
    sa.Column('id_localite', sa.Integer(), nullable=False),
    sa.Column('nom_localite', sa.String(length=150), nullable=False),
    sa.Column('code_localite', sa.String(length=30), nullable=False),
    sa.Column('id_type_localite', sa.Integer(), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_parent'], ['localite_administrative.id_localite'], ),
    sa.ForeignKeyConstraint(['id_type_localite'], ['type_localite.id_type_localite'], ),
    sa.PrimaryKeyConstraint('id_localite'),
    sa.UniqueConstraint('code_localite')
    )
    op.create_table('quartier',
    sa.Column('id_quartier', sa.Integer(), nullable=False),
    sa.Column('nom_quartier', sa.String(length=150), nullable=False),
    sa.Column('code_quartier', sa.String(length=30), nullable=False),
    sa.Column('id_localite', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_localite'], ['localite_administrative.id_localite'], ),
    sa.PrimaryKeyConstraint('id_quartier'),
    sa.UniqueConstraint('code_quartier')
    )
    op.create_table('zone_denombrement',
    sa.Column('id_zd', sa.Integer(), nullable=False),
    sa.Column('code_zd', sa.String(length=30), nullable=False),
    sa.Column('id_localite', sa.Integer(), nullable=False),
    sa.Column('id_quartier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_localite'], ['localite_administrative.id_localite'], ),
    sa.ForeignKeyConstraint(['id_quartier'], ['quartier.id_quartier'], ),
    sa.PrimaryKeyConstraint('id_zd'),
    sa.UniqueConstraint('code_zd')
    )
    with op.batch_alter_table('zone_denombrement', schema=None) as batch_op:
        batch_op.create_index('idx_zd_localite', ['id_localite'], unique=False)
        batch_op.create_index('idx_zd_quartier', ['id_quartier'], unique=False)

    op.create_table('affectation_zd',
    sa.Column('id_affectation', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_zd', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_zd'], ['zone_denombrement.id_zd'], ),
    sa.PrimaryKeyConstraint('id_affectation')
    )
    with op.batch_alter_table('affectation_zd', schema=None) as batch_op:
        batch_op.create_index('idx_affectation_user', ['id_utilisateur'], unique=False)
        batch_op.create_index('idx_affectation_zd', ['id_zd'], unique=False)

    op.create_table('ilot',
    sa.Column('id_ilot', sa.Integer(), nullable=False),
    sa.Column('numero_ilot', sa.Integer(), nullable=False),
    sa.Column('code_ilot', sa.String(length=30), nullable=False),
    sa.Column('id_zd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_zd'], ['zone_denombrement.id_zd'], ),
    sa.PrimaryKeyConstraint('id_ilot'),
    sa.UniqueConstraint('code_ilot')
    )
    with op.batch_alter_table('ilot', schema=None) as batch_op:
        batch_op.create_index('idx_ilot_zd', ['id_zd'], unique=False)

    op.create_table('logement',
    sa.Column('id_logement', sa.Integer(), nullable=False),
    sa.Column('numero_logement', sa.Integer(), nullable=False),
    sa.Column('code_logement', sa.String(length=50), nullable=False),
    sa.Column('id_ilot', sa.Integer(), nullable=False),
    sa.Column('id_type_logement', sa.Integer(), nullable=False),
    sa.Column('id_materiau_mur', sa.Integer(), nullable=False),
    sa.Column('id_materiau_toit', sa.Integer(), nullable=False),
    sa.Column('id_source_eau', sa.Integer(), nullable=False),
    sa.Column('id_type_toilette', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ilot'], ['ilot.id_ilot'], ),
    sa.ForeignKeyConstraint(['id_materiau_mur'], ['materiau_mur.id_materiau_mur'], ),
    sa.ForeignKeyConstraint(['id_materiau_toit'], ['materiau_toit.id_materiau_toit'], ),
    sa.ForeignKeyConstraint(['id_source_eau'], ['source_eau.id_source_eau'], ),
    sa.ForeignKeyConstraint(['id_type_logement'], ['type_logement.id_type_logement'], ),
    sa.ForeignKeyConstraint(['id_type_toilette'], ['type_toilette.id_type_toilette'], ),
    sa.PrimaryKeyConstraint('id_logement'),
    sa.UniqueConstraint('code_logement')
    )
    with op.batch_alter_table('logement', schema=None) as batch_op:
        batch_op.create_index('idx_logement_ilot', ['id_ilot'], unique=False)

    op.create_table('menage',
    sa.Column('id_menage', sa.Integer(), nullable=False),
    sa.Column('numero_menage', sa.Integer(), nullable=False),
    sa.Column('code_menage', sa.String(length=60), nullable=False),
    sa.Column('id_logement', sa.Integer(), nullable=False),
    sa.Column('id_statut_menage', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_logement'], ['logement.id_logement'], ),
    sa.ForeignKeyConstraint(['id_statut_menage'], ['statut_menage.id_statut_menage'], ),
    sa.PrimaryKeyConstraint('id_menage'),
    sa.UniqueConstraint('code_menage')
    )
    with op.batch_alter_table('menage', schema=None) as batch_op:
        batch_op.create_index('idx_menage_logement', ['id_logement'], unique=False)
        batch_op.create_index('idx_menage_statut', ['id_statut_menage'], unique=False)

    op.create_table('individu',
    sa.Column('id_individu', sa.Integer(), nullable=False),
    sa.Column('id_menage', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('sexe', sa.String(length=1), nullable=False),
    sa.Column('lien_chef_menage', sa.String(length=20), nullable=False),
    sa.Column('est_chef_menage', sa.Boolean(), nullable=False),
    sa.Column('situation_matrimoniale', sa.String(length=20), nullable=False),
    sa.Column('niveau_instruction', sa.String(length=20), nullable=False),
    sa.Column('statut_scolarisation', sa.String(length=20), nullable=True),
    sa.Column('statut_activite', sa.String(length=20), nullable=False),
    sa.Column('sait_lire_ecrire', sa.Boolean(), nullable=True),
    sa.Column('id_profession', sa.Integer(), nullable=True),
    sa.CheckConstraint("lien_chef_menage IN ('CHEF','CONJOINT','ENFANT','PERE_MERE','FRERE_SOEUR','AUTRE_PARENT','SANS_LIEN')", name='ck_individu_lien'),
    sa.CheckConstraint("niveau_instruction IN ('AUCUN','PRIMAIRE','SECONDAIRE_1','SECONDAIRE_2','SUPERIEUR')", name='ck_individu_instruction'),
    sa.CheckConstraint("sexe IN ('M','F')", name='ck_individu_sexe'),
    sa.CheckConstraint("situation_matrimoniale IN ('CELIBATAIRE','MARIE_MONO','MARIE_POLY','DIVORCE','VEUF','UNION_LIBRE')", name='ck_individu_matrimoniale'),
    sa.CheckConstraint("statut_activite IN ('ACTIF_OCCUPE','CHOMEUR','ELEVE_ETUDIANT','RETRAITE','MENAGERE','AUTRE_INACTIF')", name='ck_individu_activite'),
    sa.CheckConstraint("statut_scolarisation IN ('SCOLARISE','NON_SCOLARISE','JAMAIS_SCOLARISE','ABANDONNE')", name='ck_individu_scolarisation'),
    sa.ForeignKeyConstraint(['id_menage'], ['menage.id_menage'], ),
    sa.ForeignKeyConstraint(['id_profession'], ['profession.id_profession'], ),
    sa.PrimaryKeyConstraint('id_individu')
    )
    with op.batch_alter_table('individu', schema=None) as batch_op:
        batch_op.create_index('idx_individu_activite', ['statut_activite'], unique=False)
        batch_op.create_index('idx_individu_menage', ['id_menage'], unique=False)

    op.create_table('passage_collecte',
    sa.Column('id_passage', sa.Integer(), nullable=False),
    sa.Column('id_menage', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('numero_passage', sa.Integer(), nullable=False),
    sa.Column('date_passage', sa.Date(), nullable=False),
    sa.Column('heure_passage', sa.Time(), nullable=True),
    sa.Column('id_statut_passage', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_menage'], ['menage.id_menage'], ),
    sa.ForeignKeyConstraint(['id_statut_passage'], ['statut_passage.id_statut_passage'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_passage')
    )
    with op.batch_alter_table('passage_collecte', schema=None) as batch_op:
        batch_op.create_index('idx_passage_menage', ['id_menage'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passage_collecte', schema=None) as batch_op:
        batch_op.drop_index('idx_passage_menage')

    op.drop_table('passage_collecte')
    with op.batch_alter_table('individu', schema=None) as batch_op:
        batch_op.drop_index('idx_individu_menage')
        batch_op.drop_index('idx_individu_activite')

    op.drop_table('individu')
    with op.batch_alter_table('menage', schema=None) as batch_op:
        batch_op.drop_index('idx_menage_statut')
        batch_op.drop_index('idx_menage_logement')

    op.drop_table('menage')
    with op.batch_alter_table('logement', schema=None) as batch_op:
        batch_op.drop_index('idx_logement_ilot')

    op.drop_table('logement')
    with op.batch_alter_table('ilot', schema=None) as batch_op:
        batch_op.drop_index('idx_ilot_zd')

    op.drop_table('ilot')
    with op.batch_alter_table('affectation_zd', schema=None) as batch_op:
        batch_op.drop_index('idx_affectation_zd')
        batch_op.drop_index('idx_affectation_user')

    op.drop_table('affectation_zd')
    with op.batch_alter_table('zone_denombrement', schema=None) as batch_op:
        batch_op.drop_index('idx_zd_quartier')
        batch_op.drop_index('idx_zd_localite')

    op.drop_table('zone_denombrement')
    op.drop_table('quartier')
    op.drop_table('localite_administrative')
    op.drop_table('utilisateur')
    op.drop_table('type_toilette')
    op.drop_table('type_logement')
    op.drop_table('type_localite')
    op.drop_table('statut_passage')
    op.drop_table('statut_menage')
    op.drop_table('source_eau')
    op.drop_table('profession')
    op.drop_table('materiau_toit')
    op.drop_table('materiau_mur')
    # ### end Alembic commands ###
